### ISSUE TITLE
Front/Prototipação de componentes para construção de tela de administração

### ISSUE THREAD

**Issue by ArthurMeloG** [UnBArqDsw2022-2/2022.2_G2-e_Rifas_Frontend#2]
Criação no figma de telas para futuro desenvolvimento da task #1

**Comment by eliasyousef00** [comment]
Foram prototipadas 3 telas: 
1. Administração - Rifas
2. Avaliar Rifa
3. Administração - Usuários

O resultado pode ser conferido aqui: https://www.figma.com/file/C3mXyTWvGzkiCgwToXWQyi/Prot%C3%B3tipo-e-recursos?node-id=2%3A3&t=h8QtgofEMQ8lH2x3-1
